baseURL = 'https://goorm.me'
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = true
title = 'Goorm.me'
theme = "paper-mod"
enableEmoji = true

disableLanguages = ["en"]

outputs.home = ["HTML", "RSS", "JSON"]

[params]
comments = true

[params.homeInfoParams]
Title = "☁ Goorm.me ☁"
Content = "본명 이상엽, 구름입니다. 백엔드, 응용프로그램, 서버 개발자입니다."

[[menu.main]]
name = "아카이브"
url = "archives"
weight = 1

[[menu.main]]
name = "카테고리"
url = "categories"
weight = 2

[[menu.main]]
name = "태그"
url = "tags"
weight = 3

[[menu.main]]
name = "검색"
url = "search"
weight = 4
