baseURL = 'https://goorm.me'
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = true
title = 'goorm.me'
theme = "paper-mod"
enableEmoji = true

disableLanguages = ["en"]

outputs.home = ["HTML", "RSS", "JSON"]

[params]
comments = true

[params.homeInfoParams]
Title = "goorm.me"
Content = "My name is Lee Sangyeop, and I love computer."

[[menu.main]]
name = "History"
url = "history"
weight = 1

[[menu.main]]
name = "Categories"
url = "categories"
weight = 2

[[menu.main]]
name = "Tags"
url = "tags"
weight = 3

[[menu.main]]
name = "Search"
url = "search"
weight = 4
